import java.awt.BorderLayout;

/*
 * Author: Arthur T. Manning - Professor Manning  atmanning@dbq.edu
 * 
 * This is a short little program demonstrating a GUI and recursion
 * code to convert from one base to another.
 * 
 * This was created using Eclipse Oxygen.3 (4.7.3) 
 * and WindowBuilder on an iMac (High Sierra - 10.13.4)
 * 
 * The labels don't render properly in Design view for some strange reason.
 * See Recursion.java for more details and explanation.
 * 
 * Most of this code was generated by WindowBuilder.
 * 
 * 
 */
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JTextField;
import java.awt.Label;
import java.awt.Color;
import javax.swing.SwingConstants;
import javax.swing.JButton;
import java.awt.SystemColor;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Font;

public class JFrameMain extends JFrame {

	private JPanel contentPane;
	private JTextField textFieldB1;
	private JTextField textFieldB2;
	private JTextField textFieldB1Val;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					JFrameMain frame = new JFrameMain();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */
	public JFrameMain() {
		setTitle("Base to Base Conversion");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 259, 212);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(null);
		
		textFieldB1 = new JTextField();
		textFieldB1.setHorizontalAlignment(SwingConstants.CENTER);
		textFieldB1.setText("16");
		textFieldB1.setBounds(46, 68, 45, 26);
		contentPane.add(textFieldB1);
		textFieldB1.setColumns(10);
		
		textFieldB2 = new JTextField();
		textFieldB2.setHorizontalAlignment(SwingConstants.CENTER);
		textFieldB2.setText("10");
		textFieldB2.setColumns(10);
		textFieldB2.setBounds(192, 68, 45, 26);
		contentPane.add(textFieldB2);
		
		textFieldB1Val = new JTextField();
		textFieldB1Val.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
		textFieldB1Val.setHorizontalAlignment(SwingConstants.CENTER);
		textFieldB1Val.setText("25");
		textFieldB1Val.setColumns(10);
		textFieldB1Val.setBounds(10, 32, 85, 37);
		contentPane.add(textFieldB1Val);
		
		Label labelResult = new Label("Result");
		labelResult.setFont(new Font("Dialog", Font.PLAIN, 20));
		labelResult.setAlignment(Label.CENTER);
		labelResult.setBackground(Color.WHITE);
		labelResult.setBounds(125, 32, 112, 37);
		contentPane.add(labelResult);
		
		JButton btnNewButton = new JButton("Convert!");
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				
				// convert base 1 to base 2
				int base1 = Integer.parseInt(textFieldB1.getText());
				String sValB1 = textFieldB1Val.getText();
				int base2 = Integer.parseInt(textFieldB2.getText());

				
				String sAnswer = "" + Recursion.baseConvert(sValB1, base1, base2, 0); //Recursion.base2Dec(sValB1, base1);
				labelResult.setText(sAnswer);
				
			}
		});
		btnNewButton.setBounds(10, 106, 227, 29);
		contentPane.add(btnNewButton);
		
		Label label = new Label("Base1");
		label.setAlignment(Label.CENTER);
		label.setBackground(SystemColor.textHighlight);
		label.setBounds(14, 10, 81, 16);
		contentPane.add(label);
		
		Label label_1 = new Label("Base2");
		label_1.setAlignment(Label.CENTER);
		label_1.setBackground(SystemColor.textHighlight);
		label_1.setBounds(125, 10, 112, 16);
		contentPane.add(label_1);
		
		Label label_2 = new Label("Brought to you by Professor Manning");
		label_2.setAlignment(Label.CENTER);
		label_2.setFont(new Font("Dialog", Font.PLAIN, 8));
		label_2.setBounds(10, 164, 227, 16);
		contentPane.add(label_2);
	}
}
